// <auto-generated />
namespace AssetManagement.Migrations.AccountScripts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MasterMerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MasterMerge));
        
        string IMigrationMetadata.Id
        {
            get { return "201803252328324_MasterMerge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
