// <auto-generated />
namespace AssetManagement.Migrations.AccountScripts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialized_Resources_in_FacilitesModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialized_Resources_in_FacilitesModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803300506056_Initialized_Resources_in_FacilitesModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
